
-- Script 01: Creación de esquema y objetos - Joyería
DROP DATABASE IF EXISTS joyeria_db;
CREATE DATABASE joyeria_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE joyeria_db;
CREATE TABLE clientes (id_cliente INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), apellido VARCHAR(100), email VARCHAR(150) UNIQUE, telefono VARCHAR(50), direccion VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE personal (id_personal INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), apellido VARCHAR(100), cargo VARCHAR(100), email VARCHAR(150), telefono VARCHAR(50), fecha_ingreso DATE) ENGINE=InnoDB;
CREATE TABLE asistencia (id_asistencia INT AUTO_INCREMENT PRIMARY KEY, id_personal INT NOT NULL, fecha DATE NOT NULL, hora_entrada TIME NOT NULL, hora_salida TIME NULL, estado ENUM('Presente','Ausente','Tarde','Licencia') DEFAULT 'Presente', CONSTRAINT fk_asistencia_personal FOREIGN KEY (id_personal) REFERENCES personal(id_personal)) ENGINE=InnoDB;
CREATE TABLE categorias (id_categoria INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE marcas (id_marca INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE productos (id_producto INT AUTO_INCREMENT PRIMARY KEY, nombre_producto VARCHAR(150) NOT NULL, id_categoria INT NULL, id_marca INT NULL, material VARCHAR(100), precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0), tipo VARCHAR(100), CONSTRAINT fk_prod_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria), CONSTRAINT fk_prod_marca FOREIGN KEY (id_marca) REFERENCES marcas(id_marca)) ENGINE=InnoDB;
CREATE TABLE precios_historial (id_historial INT AUTO_INCREMENT PRIMARY KEY, id_producto INT NOT NULL, precio_anterior DECIMAL(10,2) NOT NULL, precio_nuevo DECIMAL(10,2) NOT NULL, motivo VARCHAR(200), fecha_cambio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_hist_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto)) ENGINE=InnoDB;
CREATE TABLE inventario (id_inventario INT AUTO_INCREMENT PRIMARY KEY, id_producto INT NOT NULL UNIQUE, cantidad_disponible INT NOT NULL DEFAULT 0, ultima_actualizacion DATE NOT NULL, CONSTRAINT fk_inv_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto)) ENGINE=InnoDB;
CREATE TABLE proveedores (id_proveedor INT AUTO_INCREMENT PRIMARY KEY, nombre_proveedor VARCHAR(150) NOT NULL, telefono VARCHAR(50), email VARCHAR(150)) ENGINE=InnoDB;
CREATE TABLE compras (id_compra INT AUTO_INCREMENT PRIMARY KEY, fecha_compra DATE NOT NULL, id_proveedor INT NOT NULL, total DECIMAL(12,2) NOT NULL, CONSTRAINT fk_compra_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor)) ENGINE=InnoDB;
CREATE TABLE detalle_compra (id_detalle_compra INT AUTO_INCREMENT PRIMARY KEY, id_compra INT NOT NULL, id_producto INT NOT NULL, cantidad INT NOT NULL CHECK (cantidad > 0), precio_unitario DECIMAL(10,2) NOT NULL, CONSTRAINT fk_dcompra_compra FOREIGN KEY (id_compra) REFERENCES compras(id_compra), CONSTRAINT fk_dcompra_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto)) ENGINE=InnoDB;
CREATE TABLE ventas (id_venta INT AUTO_INCREMENT PRIMARY KEY, fecha_venta DATETIME NOT NULL, id_cliente INT NOT NULL, id_personal INT NULL, total DECIMAL(12,2) NOT NULL, CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente), CONSTRAINT fk_venta_personal FOREIGN KEY (id_personal) REFERENCES personal(id_personal)) ENGINE=InnoDB;
CREATE TABLE detalle_venta (id_detalle_venta INT AUTO_INCREMENT PRIMARY KEY, id_venta INT NOT NULL, id_producto INT NOT NULL, cantidad INT NOT NULL CHECK (cantidad > 0), precio_unitario DECIMAL(10,2) NOT NULL, CONSTRAINT fk_dventa_venta FOREIGN KEY (id_venta) REFERENCES ventas(id_venta), CONSTRAINT fk_dventa_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto)) ENGINE=InnoDB;
CREATE TABLE metodos_pago (id_metodo_pago INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(50) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE pagos_venta (id_pago INT AUTO_INCREMENT PRIMARY KEY, id_venta INT NOT NULL, id_metodo_pago INT NOT NULL, monto DECIMAL(12,2) NOT NULL, fecha_pago DATETIME NOT NULL, CONSTRAINT fk_pago_venta FOREIGN KEY (id_venta) REFERENCES ventas(id_venta), CONSTRAINT fk_pago_metodo FOREIGN KEY (id_metodo_pago) REFERENCES metodos_pago(id_metodo_pago)) ENGINE=InnoDB;
DROP VIEW IF EXISTS vw_ventas_detalladas; CREATE VIEW vw_ventas_detalladas AS SELECT v.id_venta, v.fecha_venta, c.nombre AS cliente, c.apellido AS apellido_cliente, p.nombre_producto AS producto, dv.cantidad, dv.precio_unitario, (dv.cantidad * dv.precio_unitario) AS subtotal FROM ventas v JOIN clientes c ON v.id_cliente = c.id_cliente JOIN detalle_venta dv ON v.id_venta = dv.id_venta JOIN productos p ON dv.id_producto = p.id_producto;
DROP VIEW IF EXISTS vw_stock_actual; CREATE VIEW vw_stock_actual AS SELECT p.id_producto, p.nombre_producto AS producto, i.cantidad_disponible FROM inventario i JOIN productos p ON i.id_producto = p.id_producto;
DROP VIEW IF EXISTS vw_ventas_producto_fecha; CREATE VIEW vw_ventas_producto_fecha AS SELECT p.id_producto, p.nombre_producto, DATE(v.fecha_venta) AS fecha, SUM(dv.cantidad) AS cantidad_vendida, SUM(dv.precio_unitario * dv.cantidad) AS total_vendido FROM productos p JOIN detalle_venta dv ON p.id_producto = dv.id_producto JOIN ventas v ON dv.id_venta = v.id_venta GROUP BY p.id_producto, p.nombre_producto, DATE(v.fecha_venta);
DROP VIEW IF EXISTS vw_clientes_valor; CREATE VIEW vw_clientes_valor AS SELECT c.id_cliente, CONCAT(c.nombre,' ',c.apellido) AS cliente, COUNT(DISTINCT v.id_venta) AS compras, SUM(dv.cantidad * dv.precio_unitario) AS total_gastado FROM clientes c LEFT JOIN ventas v ON v.id_cliente = c.id_cliente LEFT JOIN detalle_venta dv ON dv.id_venta = v.id_venta GROUP BY c.id_cliente, CONCAT(c.nombre,' ',c.apellido) ORDER BY total_gastado DESC;
DROP VIEW IF EXISTS vw_rendimiento_empleados; CREATE VIEW vw_rendimiento_empleados AS SELECT pe.id_personal, CONCAT(pe.nombre,' ',pe.apellido) AS empleado, COUNT(DISTINCT v.id_venta) AS ventas_realizadas, SUM(dv.cantidad * dv.precio_unitario) AS total_vendido FROM personal pe LEFT JOIN ventas v ON v.id_personal = pe.id_personal LEFT JOIN detalle_venta dv ON dv.id_venta = v.id_venta GROUP BY pe.id_personal, CONCAT(pe.nombre,' ',pe.apellido) ORDER BY total_vendido DESC;
DROP VIEW IF EXISTS vw_pagos_por_metodo; CREATE VIEW vw_pagos_por_metodo AS SELECT mp.nombre AS metodo_pago, DATE_FORMAT(pv.fecha_pago, '%Y-%m') AS anio_mes, SUM(pv.monto) AS total_pagado FROM pagos_venta pv JOIN metodos_pago mp ON pv.id_metodo_pago = mp.id_metodo_pago GROUP BY mp.nombre, DATE_FORMAT(pv.fecha_pago, '%Y-%m') ORDER BY anio_mes, metodo_pago;
DROP VIEW IF EXISTS vw_inventario_valorizado; CREATE VIEW vw_inventario_valorizado AS SELECT p.id_producto, p.nombre_producto, i.cantidad_disponible, p.precio, (i.cantidad_disponible * p.precio) AS valor_inventario FROM inventario i JOIN productos p ON p.id_producto = i.id_producto;
DELIMITER $$
DROP FUNCTION IF EXISTS fn_total_cliente $$ CREATE FUNCTION fn_total_cliente(p_cliente INT) RETURNS DECIMAL(12,2) DETERMINISTIC BEGIN DECLARE total DECIMAL(12,2); SELECT SUM(dv.precio_unitario * dv.cantidad) INTO total FROM ventas v JOIN detalle_venta dv ON v.id_venta = dv.id_venta WHERE v.id_cliente = p_cliente; RETURN IFNULL(total, 0); END $$
DROP FUNCTION IF EXISTS fn_total_producto_dia $$ CREATE FUNCTION fn_total_producto_dia(p_producto INT, p_fecha DATE) RETURNS INT DETERMINISTIC BEGIN DECLARE total INT; SELECT SUM(dv.cantidad) INTO total FROM detalle_venta dv JOIN ventas v ON dv.id_venta = v.id_venta WHERE dv.id_producto = p_producto AND DATE(v.fecha_venta) = p_fecha; RETURN IFNULL(total, 0); END $$
DROP FUNCTION IF EXISTS fn_horas_trabajadas $$ CREATE FUNCTION fn_horas_trabajadas(p_id INT, p_fecha DATE) RETURNS DECIMAL(5,2) DETERMINISTIC BEGIN DECLARE total_horas DECIMAL(5,2); SELECT SUM(TIMESTAMPDIFF(MINUTE, hora_entrada, hora_salida)/60) INTO total_horas FROM asistencia WHERE id_personal = p_id AND fecha = p_fecha AND hora_salida IS NOT NULL; RETURN IFNULL(total_horas, 0); END $$
DROP PROCEDURE IF EXISTS sp_actualizar_precio_producto $$ CREATE PROCEDURE sp_actualizar_precio_producto(IN p_producto INT, IN p_precio DECIMAL(10,2), IN p_motivo VARCHAR(200)) BEGIN DECLARE v_precio_actual DECIMAL(10,2); SELECT precio INTO v_precio_actual FROM productos WHERE id_producto = p_producto; UPDATE productos SET precio = p_precio WHERE id_producto = p_producto; INSERT INTO precios_historial(id_producto, precio_anterior, precio_nuevo, motivo) VALUES(p_producto, v_precio_actual, p_precio, p_motivo); END $$
DROP PROCEDURE IF EXISTS sp_productos_stock_bajo $$ CREATE PROCEDURE sp_productos_stock_bajo(IN p_minimo INT) BEGIN SELECT p.id_producto, p.nombre_producto, i.cantidad_disponible FROM inventario i JOIN productos p ON i.id_producto = p.id_producto WHERE i.cantidad_disponible <= p_minimo ORDER BY i.cantidad_disponible ASC; END $$
DROP PROCEDURE IF EXISTS sp_ranking_productos_mes $$ CREATE PROCEDURE sp_ranking_productos_mes(IN p_anio INT, IN p_mes INT) BEGIN SELECT p.id_producto, p.nombre_producto, SUM(dv.cantidad) AS total_unidades, SUM(dv.precio_unitario * dv.cantidad) AS total_monto FROM detalle_venta dv JOIN ventas v ON dv.id_venta = v.id_venta JOIN productos p ON dv.id_producto = p.id_producto WHERE YEAR(v.fecha_venta) = p_anio AND MONTH(v.fecha_venta) = p_mes GROUP BY p.id_producto, p.nombre_producto ORDER BY total_unidades DESC, total_monto DESC LIMIT 10; END $$
DROP TRIGGER IF EXISTS trg_descontar_stock_venta $$ CREATE TRIGGER trg_descontar_stock_venta AFTER INSERT ON detalle_venta FOR EACH ROW BEGIN UPDATE inventario SET cantidad_disponible = cantidad_disponible - NEW.cantidad, ultima_actualizacion = CURRENT_DATE() WHERE id_producto = NEW.id_producto; END $$
DROP TRIGGER IF EXISTS trg_completar_hora_salida $$ CREATE TRIGGER trg_completar_hora_salida BEFORE UPDATE ON asistencia FOR EACH ROW BEGIN IF NEW.hora_salida IS NULL THEN SET NEW.hora_salida = '20:00:00'; END IF; END $$
DROP TRIGGER IF EXISTS trg_validar_stock $$ CREATE TRIGGER trg_validar_stock BEFORE INSERT ON detalle_venta FOR EACH ROW BEGIN DECLARE v_stock INT; SELECT cantidad_disponible INTO v_stock FROM inventario WHERE id_producto = NEW.id_producto; IF v_stock < NEW.cantidad THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Stock insuficiente'; END IF; END $$
DELIMITER ;
